### ISSUE TITLE
Repo topic ≠ project topic

### ISSUE THREAD

**Issue by sammypanda** [siennapear/DigitalSolutions#2]
**Renaming the repository, and redoing the README.md** to focus on the topic of the project, rather than the context of why the project/repo is being created.

**Comment by siennapear** [comment]
Changed it to suit the task sheet. :) thank you.

**Comment by sammypanda** [comment]
This issue should be reopened, #2 wasn't solved fully.

Refer to [my branch](https://github.com/Samdvich/Enviro-Act/) for a better practice repo topic/description relevant to the project (this would include the README.md too, I haven't adjusted that on my branch because I don't intend to make any pull requests).
